### ISSUE TITLE
.send() not working

### ISSUE THREAD

**Issue by sigmasoldi3r** [garrettjoecox/scriptserver#27] opened 2018-10-02 11:33 UTC
The `server.send('string')` method is ignored by the server.

The snippet tested:
```js
console.log('Hello world!');
server.send(`say Command tested by ${player.name}`);
```

Which produces:

```
[13:23:18] [Server thread/INFO] [minecraft/DedicatedServer]: <player> !test
Hello world!
```

But nothing in-game.

RCON is also enabled, the console yields at the startup:

```
[13:20:42] [Server thread/INFO] [minecraft/DedicatedServer]: Done (21,957s)! For help, type "help" or "?"
[13:20:42] [Server thread/INFO] [minecraft/DedicatedServer]: Starting remote control listener
[13:20:42] [RCON Listener #1/INFO] [minecraft/MinecraftServer]: RCON running on 0.0.0.0:25575
```

SpongeForge is present and installed, maybe this relates to https://github.com/garrettjoecox/scriptserver/issues/16 (Not sure)

Also I had to workaround those issues: https://github.com/garrettjoecox/scriptserver-event/issues/6 and https://github.com/garrettjoecox/scriptserver-command/issues/3 using this snippet:

```js
server.on('console', line => {
  const match = line.match(REGEX);
  if (match) {
    const [ input, timestamp, thread, title, ply, command, rawParams ] = match;
    const params = rawParams.split(' ');
    const cmdFile = path.join('scripts', 'commands', `${command}.js`);
    try {
      const player = PLAYERS[ply] || new Player(ply);
      const script = fs.readFileSync(cmdFile).toString();
      try {
        vm.runInNewContext(script, vm.createContext({
          player, input, timestamp, thread, title, command, params, server, console
        }));
      } catch (err) {
        console.error(err);
        const msg = [
          '',
          { text: 'ERROR: ', color: 'red' },
          { text: 'Command failed, reason: '},
          { text: `"${err.message}"`, color: 'red' }
        ];
        server.send(`tellraw ${ply} ${JSON.stringify(msg)}`);
      }
    } catch (err) {
      console.error(err);
      const msg = [
        '',
        { 'text': 'ERROR: ', 'color': 'red' },
        { 'text': `"${command}"`, 'italic': true },
        { 'text': ' is not a known command.' }
      ];
      server.send(`tellraw ${ply} ${JSON.stringify(msg)}`);
    }
  }
});
```

Which even on error do not report to the server, I don't know if this currently relates to the same problem.

Node v10.7.0
NPM 6.4.1
scriptserver latest
scriptserver-command latest

## Edit:

Tested `server.spawn.stdin.write` but does not work either.

**Comment by fjeddy** [comment] 2019-01-06 05:56
All of your issues seem related to the same thing.

You don't provide and connect to RCON.

**Comment by sigmasoldi3r** [comment] 2019-01-07 13:39
> 
> 
> All of your issues seem related to the same thing.
> 
> You don't provide and connect to RCON.

What do you mean?

**Comment by fjeddy** [comment] 2019-01-07 13:51
What I mean is that your configuration does not give any indication that you're actually connecting to RCON. It's not enough to just have it running server side, scriptserver also needs to connect to it.

More specifically, you're missing a `connection from localhost` line in console

```
[14:49:22 INFO]: Done (13.379s)! For help, type "help"
[14:49:22 INFO]: Starting remote control listener
[14:49:22 INFO]: RCON running on 0.0.0.0:25575
[14:49:22 INFO]: Rcon connection from: /127.0.0.1
```
If scriptserver fails to connect to rcon, then most of it will fail to work as a result. And based on your other issues and the examples you give, then it seems like you don't ever connect RCON with scriptserver at all.

**Comment by sigmasoldi3r** [comment] 2019-01-07 14:30
I'll check it out later, I don't even remember where I had the project located 😅

**Comment by garrettjoecox** [comment] 2019-06-08 12:30
Closing this as it is working correctly.

**Closed by garrettjoecox** 2019-06-08 12:30 UTC

**Comment by KDSbami** [comment] 2021-04-16 11:21
Hey, I am having the same issue. I gave all rcon params even tried connecting to default.

[16:48:03] [Server thread/INFO]: Thread RCON Listener started
[16:48:03] [Server thread/INFO]: RCON running on 0.0.0.0:25575

rcon.password=0000

rcon: {
      host: 'localhost',
      port: '25575',
      password: '0000',
      buffer: 100,
    },

**Comment by garrettjoecox** [comment] 2021-04-16 13:23
@KDSbami I’ve learned that the problem is usually with the RegExp scriptserver is waiting for. 

You can override the default one to match what your version of Minecraft outputs, the default one is here https://github.com/garrettjoecox/scriptserver/blob/ae1e000d6ba6680b66c41b7cb81250af4504aa2f/index.js#L25

**Comment by garrettjoecox** [comment] 2021-04-16 13:24
Try replacing that with a regexp that matches yours (yours is Server Info rather than Rcon Listener)

I’ve been meaning to update the docs to reflect this but havent had the time
