### ISSUE TITLE
Cannot use essentials

### ISSUE THREAD

**Issue by Bayside308** [garrettjoecox/scriptserver#28] opened 2019-06-02 23:32 UTC
Error log: https://pastebin.com/XKDky42g

When I start the server with the following script, it errors out. Disabling scriptserver-essentials prevents the error. Running with vanilla 1.14.2.

Start script (server.js): https://pastebin.com/52iUAi8p

**Comment by theusaf** [comment] 2019-06-03 00:18
The error might be fixed by adding a function on line 13 in scriptserver-json: "fs.mkdir(config.dir,err=>{if(err)console.log(err);})"

**Comment by Bayside308** [comment] 2019-06-03 01:32
It now runs, thank you! Fixed file: https://pastebin.com/BxCwFUXn

I'm now encountering a new error, however. The essentials module cannot seem to recognize that I am online. It prints the following out to me (the player) when I type "~spawn": 

"Something went wrong, please let the server admin know of the following error"
"util.getLocation: Bayside308 is not online"

There are no errors in the console.

It also cannot handle "~day" and prints: 

"Something went wrong, please let the server admin know of the following error"
"Cannot read property '1' of null"

**Comment by theusaf** [comment] 2019-06-03 02:13
The online issue is caused by the outdated server-utils package using the "tellraw" command. You need to edit it to a "list" command, and do something like "...result=>new Regex(player,"g").test(result)..." (Line 33)

I'm not sure about the "~day". Can you provide a more detailed log?

**Comment by garrettjoecox** [comment] 2019-06-08 12:31
Locally I have updated all scriptserver addons to support the new commands, I just need to clean it up a bit and publish them.. Will hopefully get around to it soon

**Comment by garrettjoecox** [comment] 2020-05-01 02:28
Updated all packages, closing this ticket.

**Closed by garrettjoecox** 2020-05-01 02:28 UTC
